[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.0"

# The title and description fields are primarily for displaying extension info in UI
title = "Plant Generator"
description="Procedurally Generates Plants"

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "./README.md"

# URL of the extension source repository.
repository = "https://github.com/Drillgon200/lsystemplants"

# One of categories for UI.
category = "Scene"

# Keywords for the extension
keywords = ["plant", "generator"]

# Icon to show in the extension manager
icon = "data/icon.png"

# Preview to show in the extension manager
preview_image = "data/preview.png"

[dependencies]
"omni.kit.uiapp" = {}
"omni.kit.mesh.raycast" = {}
"omni.ui.scene" = {}

# Main python module this extension provides, it will be publicly available as "import drillgon.scene.lsystemplants".
[[python.module]]
name = "drillgon.scene.lsystemplants"
